---
title: "Group 13 - Data Analysis Research Question v001"
author: "Al Sahabir Nur Yeamin, Earth Vangwithayakul, Mathias Mortensen & Zen Rehda"
date: "2024-11-08"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Network:
We are working with the BACI dataset from Centre d'Etudes Prospectives et d'Informations Internationales, a government funded French economic institute. The dataset provides bilateral trade information for 200 countries, divided by product types.

Network is available for download here: 

https://www.cepii.fr/CEPII/en/bdd_modele/bdd_modele_item.asp?id=37

We have decided to focus on the import and export of 250+ year old historical artifacts (product code 970610).

\vspace{8pt}

We are working based on the research question:

1. By turning a dataset of exports/imports of historical artifacts into a bipartite network(With country-nodes split into importer-nodes and exporter-nodes), what can we tell about the countries importing historical artifacts and the countries that are exporting historical artifacts? 

Sub-questions: 


- Can we find clusters of trade in historical artifacts, and what do these clusters tell us?
- Are certain countries vastly outselling others? Does this point to a selling of their history, or are they historically hoarders of artifacts?
- By looking at trade over time(comparing the most recent dataset to the oldest), which nodes grow the most?

\vspace{8pt}

\vspace{8pt}

Group Github repository: 

https://github.com/poopiboi/NA_2024_3rdSemesterProject_AllAboutNetworks