---
title: "Group 13 - Data Analysis Research Question v001"
author: "Al Sahabir Nur Yeamin, Earth Vangwithayakul, Mathias Mortensen & Zen Rehda"
date: "2024-11-08"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Network:
We are working with the BACI dataset from Centre d'Etudes Prospectives et d'Informations Internationales, a government funded French economic institute. The dataset provides bilateral trade information for 200 countries, divided by product types.

Network is available for download here: 

https://www.cepii.fr/CEPII/en/bdd_modele/bdd_modele_item.asp?id=37

We have decided to focus on the import and export of 250+ year old historical artifacts (product code 970610).

\vspace{8pt}

We are currently working on two research questions:


1. Seeing as the US has specific rules against importing artifacts of historical value from certain latin American countries (and Cyprus), in our network can we find a secondary flow of artifacts that could be used to circumvent these rules? 

2. If we turn a dataset of exports/imports of historical artifacts into a bipartite network, can we clearly visualize the main countries importing historical artifacts and the countries that are exporting historical artifacts.

\vspace{8pt}

Source for question 1: 

https://www.cbp.gov/sites/default/files/assets/documents/2020-Jun/Works%20of%20art%20etc%20ICP_0.pdf (p. 14-19) 

\vspace{8pt}

Group Github repository: 

https://github.com/poopiboi/NA_2024_3rdSemesterProject_AllAboutNetworks